### ISSUE TITLE
!helpcciaa command has 1 too many a's - Should be !helpccia

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/BOREALISbot#4]

**Comment by skull132** [comment]
`!helpcciaa` is "help CCIA Agent". Similarly to how `!helpmod` is "help Moderator", and how `!hepladmin` is "help Administrator".

Though, in version 2, these commands will be replaced with `!helpstaff`, which will display all the commands you specifically have access to. So issue will be irrelevant shortly.
